### ISSUE TITLE
Fix docs on RTD

### ISSUE THREAD

**Issue by amercader** [ckan/ckanext-spatial#128]
Failing because this:

```
Collecting Shapely>=1.2.13 (from -r doc-requirements.txt (line 4))
  Downloading Shapely-1.5.13.tar.gz (176kB)
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-wOBjbc/Shapely/setup.py", line 38, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    
```

Check this:

http://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by MartinHowitt** [comment]
I'm getting a very similar error to this when pip installing ckanext-spatial on top of the docker-ckan. Alpine seems to be persuadable to have 2 of the 3 needed geos libraries available but not py-geos, which is now python3 only. Is this an issue for ckanext-spatial or for docker-ckan?

**Comment by gitshrl** [comment]
Install required packages first worked for me

`RUN apk add --no-cache \
    gcc \
    libc-dev \
    geos-dev \
    && pip3 install -r src/ckanext-spatial/pip-requirements.txt`
