### ISSUE TITLE
[CSW Harvest] [ckanext.harvest.model] Error gathering the identifiers from the CSW server [timed out]

### ISSUE THREAD

**Issue by epardoperez** [ckan/ckanext-spatial#146]
Hello 

Frist this is my first time to report some issues, and my english is very bad.

I  installed ckanext-spatial  and ckanext-harvest and apache log have not errors, so I think the instalation is good, but when i want to create a harvest from geonetwork csw server (http://www.ideandalucia.es/catalogo/inspire/srv/eng/csw?) I get and error 

I installed ckan 2.3  on ubuntu 14.04 and ubuntu 15.10, and ckan 2.5 on ubuntu 14.04 and I have the same problem.

When I harvest form other ckan i have not problems

Sorry for my bad english

the log show

2016-01-28 19:49:06,800 DEBUG [ckanext.harvest.queue] Received harvest job id: a253254b-15e3-45ad-967d-b28007a8c8f2
2016-01-28 19:49:06,811 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] CswHarvester gather_stage for job: <HarvestJob id=a253254b-15e3-45ad-967d-b28007a8c8f2 created=2016-01-28 18:49:06.646935 gather_started=2016-01-28 18:49:06.811759 gather_finished=None finished=None source_id=bc22175c-b2bb-4119-ae6d-54d197b64958 status=Running>
2016-01-28 19:49:07,682 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] Starting gathering for http://www.ideandalucia.es/catalogo/inspire/srv/eng/csw?
2016-01-28 19:49:07,683 INFO  [ckanext.spatial.lib.csw_client] Making CSW request: getrecords2 {'typenames': 'csw:Record', 'maxrecords': 10, 'sortby': <owslib.fes.SortBy object at 0x7f83d01e68d0>, 'outputschema': 'http://www.isotc211.org/2005/gmd', 'cql': None, 'startposition': 0, 'esn': 'brief', 'constraints': []}
2016-01-28 19:49:17,866 ERROR [ckanext.spatial.harvesters.csw.CSW.gather] Exception: Traceback (most recent call last):
  File "/opt/ckan/default/src/ckanext-spatial/ckanext/spatial/harvesters/csw.py", line 95, in gather_stage
    for identifier in self.csw.getidentifiers(page=10, outputschema=self.output_schema(), cql=cql):
  File "/opt/ckan/default/src/ckanext-spatial/ckanext/spatial/lib/csw_client.py", line 127, in getidentifiers
    csw.getrecords2(**kwa)
  File "/opt/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 341, in getrecords2
    self._invoke()
  File "/opt/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 582, in _invoke
    self.response = util.http_post(self.url, self.request, self.lang, self.timeout)
  File "/opt/ckan/default/local/lib/python2.7/site-packages/owslib/util.py", line 285, in http_post
    up = urllib2.urlopen(r,timeout=timeout);
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
2016-01-28 19:49:17,884 INFO  [ckanext.harvest.model] Error gathering the identifiers from the CSW server [timed out]
2016-01-28 19:49:17,892 ERROR [ckanext.harvest.queue] Gather stage failed

**Comment by davidread** [comment]
It can't create a socket connection. It suggests that either the ``http://www.ideandalucia.es`` bit is incorrect or something else is blocking that address from the machine you're using. You could see if curl has the same problem accessing that URL from the same machine.

**Comment by davidread** [comment]
I'm closing the issue since it doesn't appear to be a problem with ckanext-spatial.

**Comment by epardoperez** [comment]
http://www.ideandalucia.es it's work and geonetwork too, but the csw server of geonetwork have a problem.

We have  a problem in the conection pool to postgresql database, We restart tomcat istance and ckanext-spatial csw harvest work 

Sorry create this issue, and thx for close

**Comment by davidread** [comment]
Great to hear it's sorted now
