### ISSUE TITLE
VDM only works with SQLAlchemy versions 0.4 through 0.8, not: 1.0.14

### ISSUE THREAD

**Issue by coreyerickson** [ckan/ckanext-spatial#158]
Attempting to setup a new installation of ckanext-spatial on ckan 2.5.2

After running the requirements install we are encountering the following error running the spatial initdb command

pip install -U -r pip-requirements.txt

paster --plugin=ckanext-spatial spatial initdb 4326 -c /etc/ckan/default/development.ini

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/command.py", line 101, in run
    command = commands[command_name].load()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/commands/spatial.py", line 6, in <module>
    from ckan.lib.cli import CkanCommand
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 12, in <module>
    import ckan.logic as logic
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 8, in <module>
    import ckan.model as model
  File "/usr/lib/ckan/default/src/ckan/ckan/model/__init__.py", line 7, in <module>
    import vdm.sqlalchemy
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/vdm/sqlalchemy/__init__.py", line 32, in <module>
    from tools import Repository
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/vdm/sqlalchemy/tools.py", line 34, in <module>
    raise ValueError("VDM only works with SQLAlchemy versions 0.4 through 0.8, not: %s" % sqav)
ValueError: VDM only works with SQLAlchemy versions 0.4 through 0.8, not: 1.0.14

Could this be a matter of VDM needing to updated ?

**Comment by davidread** [comment]
Of course vdm should be checked over to see if it is compatible with sqlalchemy 1.0. Feel free...

But in the meantime:

> pip install -U -r pip-requirements.txt

Get rid of the `-U` - I'm pretty sure it doesn't say that in the docs anywhere. It will cause all sorts of unwanted upgrades, including sqlalchemy. You want SQLAlchemy==0.9.6, as it says in the ckan requirements file. I should start again with a fresh virtual env, if I was you...

The vdm message is actually incorrect - it should say it supports up to v0.9 - I've just fixed that on master, so thanks for spotting that.

**Comment by coreyerickson** [comment]
Well now that explains it, I am not sure how the -U worked into our process today but it did. Thanks for spotting that :)

We will start over with a fresh venv

**Comment by malthe** [comment]
Note that vdm now supports SQLAlchemy up to 1.3: https://pypi.org/project/vdm/0.15/.

**Comment by Zharktas** [comment]
However VDM is removed completely from ckan 2.9 https://github.com/ckan/ckan/pull/4784
