### ISSUE TITLE
CSW gmd schema location error

### ISSUE THREAD

**Issue by sirex** [ckan/ckanext-spatial#180]
I'm trying to set up harvester for https://www.geoportal.lt/inspire-geoportal/csw?Request=GetCapabilities&Service=CSW&Version=2.0.2 but I get following error:

    $ paster --plugin=ckanext-harvest harvester run_test 1bfd21fe-96aa-425e-9c79-f300bb8bd00a -c /etc/ckan/default/production.ini 
    2017-08-17 16:59:18,539 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] Starting gathering for https://www.geoportal.lt/inspire-geoportal/csw
    2017-08-17 16:59:18,539 INFO  [ckanext.spatial.lib.csw_client] Making CSW request: getrecords2 {'typenames': 'csw:Record', 'maxrecords': 10, 'sortby': <owslib.fes.SortBy object at 0x7f5c98289610>, 'outputschema': 'http://www.isotc211.org/2005/gmd', 'cql': None, 'startposition': 0, 'esn': 'brief', 'constraints': []}
    2017-08-17 16:59:18,663 ERROR [ckanext.spatial.harvesters.csw.CSW.gather] Exception: Traceback (most recent call last):
        File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/harvesters/csw.py", line 95, in gather_stage
        for identifier in self.csw.getidentifiers(page=10, outputschema=self.output_schema(), cql=cql):
        File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/lib/csw_client.py", line 127, in getidentifiers
        csw.getrecords2(**kwa)
        File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 341, in getrecords2
        self._invoke()
        File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 585, in _invoke
        self._exml = etree.parse(StringIO.StringIO(self.response))
        File "src/lxml/lxml.etree.pyx", line 3442, in lxml.etree.parse (src/lxml/lxml.etree.c:81716)
        File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118859)
        File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:119128)
        File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117808)
        File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:112052)
        File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105896)
        File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:107604)
        File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:106458)
    XMLSyntaxError: xmlns:schemaLocation: 'http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd' is not a valid URI, line 5, column 260 (line 5)
    2017-08-17 16:59:18,672 INFO  [ckanext.harvest.model] Error gathering the identifiers from the CSW server [xmlns:schemaLocation: 'http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd' is not a valid URI, line 5, column 260 (line 5)]

I tried to check if all URI work and http://www.isotc211.org/2005/gmd redirects to http://www.isotc211.org/2005/gmd/ (adds slash at the end), maybe redirect is the issue? I tried to add slash to avoid redirect, then I get another error:

    $ paster --plugin=ckanext-harvest harvester run_test 1bfd21fe-96aa-425e-9c79-f300bb8bd00a -c /etc/ckan/default/production.ini 
    2017-08-17 17:10:07,878 DEBUG [ckanext.spatial.harvesters.csw.CSW.gather] Starting gathering for https://www.geoportal.lt/inspire-geoportal/csw
    2017-08-17 17:10:07,879 INFO  [ckanext.spatial.lib.csw_client] Making CSW request: getrecords2 {'typenames': 'csw:Record', 'maxrecords': 10, 'sortby': <owslib.fes.SortBy object at 0x7fbf0bdb2150>, 'outputschema': 'http://www.isotc211.org/2005/gmd/', 'cql': None, 'startposition': 0, 'esn': 'brief', 'constraints': []}
    2017-08-17 17:10:07,941 ERROR [ckanext.spatial.harvesters.csw.CSW.gather] Exception: Traceback (most recent call last):
    File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/harvesters/csw.py", line 95, in gather_stage
        for identifier in self.csw.getidentifiers(page=10, outputschema=self.output_schema(), cql=cql):
    File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/lib/csw_client.py", line 127, in getidentifiers
        csw.getrecords2(**kwa)
    File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 341, in getrecords2
        self._invoke()
    File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/owslib/csw.py", line 605, in _invoke
        raise ows.ExceptionReport(self._exml, self.owscommon.namespace)
    ExceptionReport: 'Invalid parameter value: locator=outputSchema'
    2017-08-17 17:10:07,952 INFO  [ckanext.harvest.model] Error gathering the identifiers from the CSW server ['Invalid parameter value: locator=outputSchema']

Does anyone have any clues about what is going on?

**Comment by kalxas** [comment]
This looks like a problem with the CSW server you are harvesting from. @tomkralidis

**Comment by kalxas** [comment]
@sirex can you please let us know the version of libxml on your system?

**Comment by sirex** [comment]
@kalxas 

    $ pip freeze | grep lxml
    lxml==3.8.0

    $ dpkg -l 'libxml2'
    [...]
    ii  libxml2:amd64                     2.9.3+dfsg1-1ubuntu0. amd64                 GNOME XML library

    $ cat /etc/issue
    Ubuntu 16.04.2 LTS \n \l

**Comment by sirex** [comment]
Ok, after some more digging I found the issue. It seems, that geoportal.lt gives invalid XML:

```xml
<gmd:MD_Metadata
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:gmd="http://www.isotc211.org/2005/gmd"
    xmlns:schemaLocation="http://www.isotc211.org/2005/gmd http://schemas.opengis.net/iso/19139/20060504/gmd/gmd.xsd">
```

Here `xmlns:schemaLocation` should be `xsi:schemaLocation`, because `xmlns:*` should point to a URI and here it points to two URIs separated by space.

I'm trying to find out if CSW service owner can fix that. But in case if they can't fix it, then how could I fix it on my part?

Maybe owslib could give a possibility to clean XML before parsing? Then I could replace all `xmlns:schemaLocation` to `xsi:schemaLocation` and everything should work. What do you think?

**Comment by tomkralidis** [comment]
This is simply bad XML and should be fixed independent of OWSLib.

**Comment by sirex** [comment]
OK, then I'm closing this issue, because the bug is not on ckanext-spatial nor on OWSLib side. Thanks.
