### ISSUE TITLE
Install on debian12 fails

### ISSUE THREAD

**Issue by armin11** [ckan/ckanext-spatial#323]
When try to install it in the ckan 2.10.3 under debian 12 -  the installation fails with following error:

 (default) ckan@debian:/usr/lib/ckan/default/src$ pip install -e "git+https://github.com/ckan/ckanext-spatial.git#egg=ckanext-spatial"
Obtaining ckanext-spatial from git+https://github.com/ckan/ckanext-spatial.git#egg=ckanext-spatial
  Updating /usr/lib/ckan/default/src/ckanext-spatial clone
  Running command git fetch -q --tags
  Running command git reset --hard -q 938308469892e4bcf7389cb4adee5ccdd5a0ccca
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/ckan/default/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/ckan/default/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/ckan/default/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gmm2uv4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gmm2uv4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gmm2uv4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gmm2uv4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-gmm2uv4x/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'ckanext.spatial'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

adopted package list for apt:
apt-get install python3-dev libxml2-dev libxslt1-dev libgeos-c1v5

other extensions like ckanext-scheming work as expected

best regards from germany,

armin

**Comment by armin11** [comment]
Seems to need some of the dev requirements: after pip install -r /usr/lib/ckan/default/src/ckan/dev-requirements.txt
it installs !
