### ISSUE TITLE
ModuleNotFoundError: No module named 'ckanext.spatial' on extension installation

### ISSUE THREAD

**Issue by gatiszeiris** [ckan/ckanext-spatial#333]
Try to install ckanext-spatial extension I always get the same error. Python version 3.8. Ckan version 2.10.1

Also try install from master branch the same error.

(default) [ckan-user@ckan2-10 src]$ pip install -e "git+https://github.com/ckan/ckanext-spatial.git@v2.1.1#egg=ckanext-spatial"
WARNING: Ignoring invalid distribution -kanext-latvian-theme-v2 (/usr/lib/ckan/default/lib/python3.8/site-packages)
Obtaining ckanext-spatial from git+https://github.com/ckan/ckanext-spatial.git@v2.1.1#egg=ckanext-spatial
  Cloning https://github.com/ckan/ckanext-spatial.git (to revision v2.1.1) to ./ckanext-spatial
  Running command git clone --filter=blob:none --quiet https://github.com/ckan/ckanext-spatial.git /usr/lib/ckan/default/src/ckanext-spatial
  Running command git checkout -q 938308469892e4bcf7389cb4adee5ccdd5a0ccca
  Resolved https://github.com/ckan/ckanext-spatial.git to commit 938308469892e4bcf7389cb4adee5ccdd5a0ccca
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/ckan/default/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/ckan/default/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/ckan/default/lib64/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-0aq07msc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 458, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-0aq07msc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-0aq07msc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-0aq07msc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-0aq07msc/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
      ModuleNotFoundError: No module named 'ckanext.spatial'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by emiliopardo** [comment]
I have the same problem :(

**Comment by gatiszeiris** [comment]
We use CKAN 2.10.1

**Comment by mutantsan** [comment]
@gatiszeiris try to install the latest version of the `ckanext-spatial` from the last commit. Does it work for you?
