### ISSUE TITLE
PostgresSQL 9.1, CKAN 2.2 Ubuntu installation

### ISSUE THREAD

**Issue by abhims** [ckan/ckanext-spatial#60]
When I try to run

paster --plugin=ckanext-spatial spatial initdb 4326 --config=/etc/ckan/default/development.ini 

I get a exception trace with the error: 

Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/paster", line 9, in <module>
    load_entry_point('PasteScript==1.7.5', 'console_scripts', 'paster')()
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 104, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 143, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/paste/script/command.py", line 238, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-spatial/ckanext/spatial/commands/spatial.py", line 38, in command
    self._load_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/cli.py", line 96, in _load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 232, in load_environment
    p.load_all(config)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 124, in load_all
    unload_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 182, in unload_all
    unload(_reversed(_PLUGINS))
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 210, in unload
    plugins_update()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 116, in plugins_update
    environment.update_config()
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 351, in update_config
    engine = sqlalchemy.engine_from_config(config, 'sqlalchemy.', *_extras)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 292, in engine_from_config
    return create_engine(url, *_opts)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/**init**.py", line 274, in create_engine
    return strategy.create(_args, **kwargs)
  File "/usr/lib/ckan/default/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 141, in create
    engineclass.**name**))
TypeError: Invalid argument(s) 'client_encoding' sent to create_engine(), using configuration PGDialect_psycopg2/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

The fix is in /usr/lib/ckan/default/src/ckan/ckan/config/environment.py line 347.

```
    #extras = {'client_encoding': 'utf8'}
    extras = {'encoding': 'utf8'}
```

The client_encoding name will cause errors in PostgresSQL.

**Comment by boykoc** [comment]
I accidentally stumbled onto this issue. The above "fix" did get things working (although in CKAN 2.8.2 the line looks like `engine = sqlalchemy.engine_from_config(config, client_encoding='utf8')` now).

But this didn't feel right to be honest. 

I realized I was trying to run my extension's tests in the ckan directory (_whooops_) which caused this issue. If I made the change above with the same command I didn't get the same error/crash but instead many tests started failing.  I reverted the change, moved to my extensions directory, ran the tests (`nosetests --nologcapture --with-pylons=test.ini
`) and it worked fine. I then went back to ckan core directory (e.g. `/usr/lib/ckan/default/src/ckan`) and ran the tests with the [doc's commands](https://docs.ckan.org/en/2.8/contributing/test.html#run-the-tests) (`nosetests --ckan --with-pylons=test-core.ini ckan ckanext`) and the tests ran fine - well as good as is typical for CKAN ;)
